name: Infra Deployment

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    paths:
      - 'deploy/**'
  workflow_dispatch:

permissions: 
  id-token: write

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_REGION: 'switzerlandnorth'

jobs:
  Preview:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Preview Deployment
        uses: azure/bicep-deploy@bed0974555908ee0609c2b50aceb984cb50ea68b
        with:
          type: deployment
          operation: whatIf
          name: ${{ github.run_id }}
          location: ${{ env.AZURE_REGION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: deploy/main.bicep
          parameters: |
            {
              "subIdAcr": "${{ secrets.AZURE_SUBSCRIPTION_ID_SS }}",
              "subIdSampleSql": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
  Prod:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    needs: Preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Prod Deployment
        uses: azure/bicep-deploy@bed0974555908ee0609c2b50aceb984cb50ea68b
        with:
          type: deployment
          operation: create
          name: ${{ github.run_id }}
          location: ${{ env.AZURE_REGION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: deploy/main.bicep
          parameters: |
            {
              "subIdAcr": "${{ secrets.AZURE_SUBSCRIPTION_ID_SS }}",
              "subIdSampleSql": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }